services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - coms-network

  coms:
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - coms-network

  test:
    build: .
    command: ["go", "test", "./tests/..."]
    volumes:
      - ./server:/app
      - ./tests:/app/tests
    depends_on:
      - coms
      - db
    environment:
      - ENV=test
    networks:
      - coms-network

networks:
  coms-network:
    name: coms-network
    driver: bridge

volumes:
  dbdata:
